spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: false  #true로하면 1부터 시작하는 인덱스 파라미터 설정. 반환값의 pageable은 반영안됨 ㅠ

logging.level:
  #org.hibernate.SQL: debug
  org.hibernate.type: trace